### PR TITLE
Regenerate all mocks and add reminder to PR template

### PR DESCRIPTION
**Pull request by StefanCholakov**
Changes proposed in this pull request:
- Regenerate all mocks with mockery 2.9.0
- Add reminder to PR template

### CODE REVIEW

**Comment by alextargov** [comment]
It's great that we're fixing the mockery version. 🎉🚀

**Review by alextargov — APPROVED** [review]

**Review by alextargov — APPROVED** [review]

**Review by alextargov — APPROVED** [review]

**Review by alextargov — APPROVED** [review]

**Review by nkanchev — APPROVED** [review]

**Pull request merged**
