### PR TITLE
[HOTFIX] Fix bundle nil pointer version

### PR DESCRIPTION
**Pull request by dragobt**
**Description**

Changes proposed in this pull request:
- adapt logic if version for bundles is null

**Related issue(s)**

- ...

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [ ] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by kaloyanspiridonov — APPROVED** [review]

**Comment by dragobt** [comment]
reset-vm
/test pre-main-compass-integration-with-dump

**Review by kaloyanspiridonov — APPROVED** [review]

**Pull request merged**
