### PR TITLE
Adjust validate script for arm and amd arch builds

### PR DESCRIPTION
**Pull request by dzahariev**
**Description**
Schema Migrator validation require buildX library, otherwise target architecture was not detected.

Changes proposed in this pull request:
- Adjust validate script for arm and amd arch builds

**Pull Request status**
- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by kaloyanspiridonov — DISMISSED** [review]

**Comment by dzahariev** [comment]
reset-vm
/test pre-main-compass-integration-with-dump

**Review by kaloyanspiridonov — APPROVED** [review]

**Pull request merged**
