### PR TITLE
Fix Resync API with generate FA constraint attached

### PR DESCRIPTION
**Pull request by ivantenevvasilev**
**Description**
When there is a constraint with type `GENERATE_FORMATION_ASSIGNMENT_NOTIFICATION` attached to a participant in the formation and the resync API is called, the constraint throws an error rather than not generating a notification. It should just skip the notification, not throw an error. 

Changes proposed in this pull request:
- change the error to a non-fatal one and just skip the generation of a FA notification

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [x] [N/A] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] [N/A] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by ivantenevvasilev** [comment]
reset-vm

**Review by StanislavStefanov — APPROVED** [review]

**Pull request merged**
