### PR TITLE
Fix tests and add logic in self reg mgr

### PR DESCRIPTION
**Pull request by alextargov**
**Description**

Changes proposed in this pull request:
- Remove Self Registration flow for every e2e test and leave it as it is only for a few SelfReg cases.
- In SelfReg Manager allow requests to continue if the flow is Certificate flow but there is no distinguished (self reg) label

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by NickyMateev — DISMISSED** [review]

**Review by StefanCholakov — DISMISSED** [review]

**Review by NickyMateev — APPROVED** [review]

**Review by PetarTodorovv — COMMENTED** [review]
And a few small things from the [initial PR](https://github.com/kyma-incubator/compass/pull/2357/)

https://github.com/kyma-incubator/compass/blob/bad45e9c8cac7a592957d93bebcbeba886b7dd7f/tests/director/tests/runtime_api_test.go#L132-L143 -> I guess it's a leftover?

https://github.com/kyma-incubator/compass/blob/bad45e9c8cac7a592957d93bebcbeba886b7dd7f/chart/compass/templates/tests/ord-service/ord-service-test.yaml#L179-L182 -> Why do we need these two new variables here? We already have the same values in the SUBSCRIPTION_CONFIG_PROVIDER_LABEL_KEY and SUBSCRIPTION_CONFIG_PROVIDER_ID ?

https://github.com/kyma-incubator/compass/blob/bad45e9c8cac7a592957d93bebcbeba886b7dd7f/tests/ord-service/tests/subscription_flow_test.go#L336-L340 -> Isn't the new label obsolete? It seems to duplicate the key-value from testConfig.ProviderLabelKey and testConfig.ProviderID ?

**Review by NickyMateev — APPROVED** [review]

**Review by StefanCholakov — APPROVED** [review]

**Review by KirilKabakchiev — APPROVED** [review]

**Pull request merged**
