### PR TITLE
remove asa mutations

### PR DESCRIPTION
**Pull request by StanislavStefanov**
**Description**

Changes proposed in this pull request:
- remove ASA mutations

**Pull Request status**
- [X] Implementation
- [X] Unit tests
- [X] `chart/compass/values.yaml` is updated

### CODE REVIEW

**Comment by StanislavStefanov** [comment]
reset-vm

**Comment by StanislavStefanov** [comment]
reset-vm

**Review by ivantenevvasilev — APPROVED** [review]

**Review by PetarTodorovv — DISMISSED** [review]

**Review by PetarTodorovv — DISMISSED** [review]

**Review by nkanchev — APPROVED** [review]

**Review by PetarTodorovv — APPROVED** [review]

**Pull request merged**
