### PR TITLE
Fix Authenticator unit test

### PR DESCRIPTION
**Pull request by ivantenevvasilev**
**Description**

Changes proposed in this pull request:
- fix `TestAuthenticator_Handler` unit test 

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [x] [N/A] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] [N/A] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by StanislavStefanov — DISMISSED** [review]

**Review by StanislavStefanov — APPROVED** [review]

**Review by PetarTodorovv — DISMISSED** [review]

**Review by StanislavStefanov — APPROVED** [review]

**Comment by ivantenevvasilev** [comment]
Will be added as part of #2484

**Pull request closed without merging**
