### PR TITLE
Bump Dependencies of Operation Controller

### PR DESCRIPTION
**Pull request by dzahariev**
**Description**
Changes proposed in this pull request:
- Operation Controller update
- Operation Controller test adopted here: https://github.com/kyma-project/test-infra/pull/6332

**Pull Request status**
- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by dzahariev** [comment]
@dekiel, the jobs  pull-compass-vpathguard and pull-compass-pjtester look that are not well configured. Can you please check this.

**Review by NickyMateev — DISMISSED** [review]

**Review by NickyMateev — APPROVED** [review]

**Review by nyordanoff — APPROVED** [review]

**Pull request merged**
