### PR TITLE
Skip sending duplicate tenant mapping notifications

### PR DESCRIPTION
**Pull request by DimitarPetrov**
**Description**

Currently, when a notification receiver (forward assignment) returns config synchronously, we recursively process the reverse assignment. We should not process it a second time, as it will result in out-of-order notifications (first with config then without) in the sync case.

This is unavoidable in the async case and the receiver should take care of the wrong order. However, in the sync case, we can do it on their behalf.

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [ ] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by DimitarPetrov** [comment]
reset-vm

**Review by PetarTodorovv — APPROVED** [review]

**Pull request merged**
