### PR TITLE
Do not allow systems merge if there are existing formations associated with the source system

### PR DESCRIPTION
**Pull request by kaloyanspiridonov**
**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [ ] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by alextargov — APPROVED** [review]

**Comment by kaloyanspiridonov** [comment]
reset-vm

**Review by alextargov — APPROVED** [review]

**Review by DimitarPetrov — APPROVED** [review]

**Pull request merged**
