### PR TITLE
Fix formation constraint list for formation template

### PR DESCRIPTION
**Pull request by StanislavStefanov**
**Description**

Changes proposed in this pull request:
- Check if there are any constraint ids in the slice before executing sql query

**Pull Request status**

- [X] Implementation
- [X] Unit tests
- [X] Integration tests
- [X] `chart/compass/values.yaml` is updated

### CODE REVIEW

**Comment by StanislavStefanov** [comment]
reset-vm

**Review by PetarTodorovv — APPROVED** [review]

**Review by PetarTodorovv — APPROVED** [review]

**Pull request merged**
