### PR TITLE
[HOTFIX] Handle ord aggregator failure

### PR DESCRIPTION
**Pull request by kaloyanspiridonov**
**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by kaloyanspiridonov** [comment]
reset-vm

**Comment by PetarTodorovv** [comment]
Not applicable

**Pull request closed without merging**
