### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by akrausesap**
**Description**

Changes proposed in this pull request:

- Added create namespace to helm installation

**Related issue(s)**
N/A

### CODE REVIEW

**Comment by akrausesap** [comment]
actually it looks like this is not enough. makes the chart install but config is using non-working defaults

**Comment by klaudiagrz** [comment]
@pkosiec Can you help with this one?

**Comment by pkosiec** [comment]
HI @akrausesap, which Helm version do you use? Helm 2.10 does create a namespace, if you specify one that doesn't exist. AFAIK this behavior is changed in Helm 3.

> actually it looks like this is not enough. makes the chart install but config is using non-working defaults

What do you mean by `non-working` defaults? What doesn't work for you?

**Comment by DimitarPetrov** [comment]
Closed due to inactivity.

**Pull request closed without merging**
