### PR TITLE
[NGPBUG-356643] Requests to SLIS fail with 414 URI Too Long

### PR DESCRIPTION
**Pull request by emmakarova**
**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by kaloyanspiridonov — APPROVED** [review]

**Comment by emmakarova** [comment]
reset-vm

**Review by kaloyanspiridonov — APPROVED** [review]

**Pull request merged**
