### PR TITLE
Propagate scenario group description from BTP System Landscape to TMS

### PR DESCRIPTION
**Pull request by dragobt**
**Description**
Currently when selecting scenario groups for S/4 tokens in BTP Cockpit we send either of the following keys to Extension Service's Token Management Service (TMS):
- UNRESTRICTED
- EVENT_MESH

To eliminate the need for Extension Service to keep a mapping for those keys to the same user-facing names like the ones in the BTP Cockpit we've agreed to propagate the user-facing names to TMS as well. From there Extension Service can reuse the name in S/4.

Changes proposed in this pull request:
- Send scenario groups as objects instead of strings
- Update  dependencies

**Related issue(s)**

- ...

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [ ] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by dzahariev — APPROVED** [review]

**Review by dzahariev — APPROVED** [review]

**Review by dzahariev — CHANGES_REQUESTED** [review]
We need to make it compatible to achieve easier delivery. 
Inside components/director/internal/domain/onetimetoken/service.go on line 433 can catch the error when parsing and to fallback to old approach.

**Review by dzahariev — DISMISSED** [review]

**Review by la4ezar — CHANGES_REQUESTED** [review]

**Review by la4ezar — APPROVED** [review]

**Review by emmakarova — APPROVED** [review]

**Pull request merged**
