### PR TITLE
Regenerate mocks using automated scripts

### PR DESCRIPTION
**Pull request by krasish**
**Description**
The heading says it all :)

**Pull Request status**

- [X] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by desislavaa — DISMISSED** [review]
Bump the director version in `values.yaml`

**Review by PetarTodorovv — APPROVED** [review]

**Pull request merged**
