### PR TITLE
[CMP-2799] Add placeholders to AppTmpl

### PR DESCRIPTION
**Pull request by dzahariev**
**Description**
Changes proposed in this pull request:
- Add placeholders to AppTmpl

**Pull Request status**
- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by dzahariev** [comment]
The change is ready for review beside the new example that will be added in a while after the examples are regenerated.

**Review by nkanchev — APPROVED** [review]

**Review by nkanchev — DISMISSED** [review]

**Comment by dzahariev** [comment]
wait for https://github.com/kyma-incubator/compass/pull/2762

**Review by StanislavStefanov — APPROVED** [review]

**Review by nkanchev — APPROVED** [review]

**Review by NickyMateev — APPROVED** [review]

**Pull request merged**
