### PR TITLE
Decline test execution if another CTS object is present in the cluster

### PR DESCRIPTION
**Pull request by dzahariev**
**Description**

Changes proposed in this pull request:
- Decline test execution if another CTS object is present in the cluster. The corner case when this was possible was if the second CTS object is created before "status" for the first to be able to take any of values "Succeeded", "Failed" or "Error".

**Pull Request status**
- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by DimitarPetrov — APPROVED** [review]

**Review by emmakarova — DISMISSED** [review]

**Comment by dzahariev** [comment]
vm-reset
/retest

**Comment by dzahariev** [comment]
reset-vm
/retest

**Comment by dzahariev** [comment]
reset-vm
/retest

**Comment by dzahariev** [comment]
reset-vm
/retest

**Review by emmakarova — APPROVED** [review]

**Review by DimitarPetrov — APPROVED** [review]

**Pull request merged**
