### PR TITLE
[HOTFIX] Change http method on the status API

### PR DESCRIPTION
**Pull request by PetarTodorovv**
**Description**
Wrongly configured HTTP methods on the status API. This PR fixes them.

**Related issue(s)**

- https://github.com/kyma-incubator/compass/pull/2886
- https://github.com/kyma-incubator/compass/pull/2930

**Pull Request status**

- [x] Implementation
- [x] [N/A] Unit tests
- [x] [N/A] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] [N/A] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by DimitarPetrov — APPROVED** [review]

**Review by DimitarPetrov — APPROVED** [review]

**Comment by PetarTodorovv** [comment]
reset-vm

**Review by DimitarPetrov — APPROVED** [review]

**Comment by PetarTodorovv** [comment]
reset-vm

**Pull request merged**
