### PR TITLE
Add postgres chart

### PR DESCRIPTION
**Pull request by kfurgol**
**Description**

Changes proposed in this pull request:

- Added Postgres chart 

**Related issue(s)**

### CODE REVIEW

**Comment by crabtree** [comment]
What about the possibility to disable the installation of this chart? As I understand correctly, the issue #80 also covers the possibility to switch between using in-cluster Postgres or externally provided one.

**Comment by kfurgol** [comment]
> What about the possibility to disable the installation of this chart? As I understand correctly, the issue #80 also covers the possibility to switch between using in-cluster Postgres or externally provided one.

It can be done by setting `storage.useEmbedded` value to `false` in  `values.yaml` file  of Compass chart

**Comment by crabtree** [comment]
> > What about the possibility to disable the installation of this chart? As I understand correctly, the issue #80 also covers the possibility to switch between using in-cluster Postgres or externally provided one.
> 
> It can be done by setting `storage.useEmbedded` value to `false` in `values.yaml` file of Compass chart

Ok, so please put this into the documentation. I would suggest creating a README file under compass chart directory.

**Comment by kfurgol** [comment]
> > > What about the possibility to disable the installation of this chart? As I understand correctly, the issue #80 also covers the possibility to switch between using in-cluster Postgres or externally provided one.
> > 
> > 
> > It can be done by setting `storage.useEmbedded` value to `false` in `values.yaml` file of Compass chart
> 
> Ok, so please put this into the documentation. I would suggest creating a README file under compass chart directory.

Done

**Pull request merged**
