### PR TITLE
Refactor Application Template model

### PR DESCRIPTION
**Pull request by dzahariev**
**Description**

Changes proposed in this pull request:
- Introduce separate Input type for Application Template scenario

**Pull Request status**
- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by dzahariev** [comment]
reset-vm
/test pre-main-compass-integration-with-dump

**Comment by dzahariev** [comment]
reset-vm
/test pre-main-compass-integration-with-dump

**Comment by dzahariev** [comment]
reset-vm
/test pre-main-compass-integration-with-dump

**Comment by dzahariev** [comment]
reset-vm
/test pre-main-compass-integration-with-dump

**Review by nyordanoff — APPROVED** [review]

**Review by kaloyanspiridonov — APPROVED** [review]

**Pull request merged**
