### PR TITLE
Fix invalid cast in ns-adapter tests

### PR DESCRIPTION
**Pull request by StefanCholakov**
**Description**

Changes proposed in this pull request:
- Fix invalid cast in ns-adapter tests

**Pull Request status**

- [x] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by nyordanoff — APPROVED** [review]

**Comment by nyordanoff** [comment]
The benchmark job will always fail because the compass from main cannot be installed - this PR fixes that.

**Review by desislavaa — APPROVED** [review]

**Review by alextargov — APPROVED** [review]

**Pull request merged**
