### PR TITLE
ORD Aggregator doesn't send Tenant header when fetching resource definitions for multitenant ORD application

### PR DESCRIPTION
**Pull request by dragobt**
**Description**

Changes proposed in this pull request:
- Send `Tenant_Id` header as fetching resource definitions for multitenant ORD application
- Update dependencies

**Related issue(s)**

**Pull Request status**

- [X] Implementation
- [X] Unit tests
- [ ] Integration tests
- [X] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by dragobt** [comment]
reset-vm

**Comment by dragobt** [comment]
reset-vm

**Review by la4ezar — APPROVED** [review]

**Review by alextargov — APPROVED** [review]

**Review by la4ezar — APPROVED** [review]

**Review by la4ezar — APPROVED** [review]

**Review by alextargov — APPROVED** [review]

**Pull request merged**
