### PR TITLE
Adopt newest ORD Version

### PR DESCRIPTION
**Pull request by dzahariev**
**Description**

Changes proposed in this pull request:
- Version 1.1.1 (shortDescription limit increased from 130 to 180 by spec. We already have a limit of 256)
- Version 1.1.2 (title limit fixed to 255 by spec)

**Pull Request status**
- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by dzahariev** [comment]
Any ideas what went wrong?

```
...
Install Compass
Path to compass charts:  /home/prow/go/src/github.com/kyma-incubator/compass/installation/scripts/../../chart/compass
Release "compass" does not exist. Installing it now.
...
NAME: compass
LAST DEPLOYED: Wed Feb 22 17:54:38 2023
NAMESPACE: compass-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
...
```

**Review by DimitarPetrov — APPROVED** [review]

**Review by kaloyanspiridonov — APPROVED** [review]

**Review by DimitarPetrov — APPROVED** [review]

**Comment by dzahariev** [comment]
reset-vm
/test pre-main-compass-integration-with-dump

**Pull request merged**
