### PR TITLE
Introduce Managed Application Provider Operator consumer type

### PR DESCRIPTION
**Pull request by kaloyanspiridonov**
**Description**

Changes proposed in this pull request:
- Introduce Managed Application Provider Operator consumer type, that will be used by Managed Application Provider operator

**Related issue(s)**

- ...

**Pull Request status**

- [x] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by alextargov** [comment]
reset-vm

**Comment by alextargov** [comment]
reset-vm

**Review by PetarTodorovv — APPROVED** [review]

**Pull request merged**
