### PR TITLE
Add ID field to ApplicationFromTemplateInput

### PR DESCRIPTION
**Pull request by georgifarashev**
**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by StanislavStefanov** [comment]
reset-vm

**Review by NickyMateev — APPROVED** [review]

**Comment by StanislavStefanov** [comment]
reset-vm

**Review by StanislavStefanov — APPROVED** [review]

**Pull request merged**
