### PR TITLE
Upgrade base image to go version 1.18

### PR DESCRIPTION
**Pull request by NickyMateev**
**Description**

All compass components have an associated Dockerfile - the base images of all was bumped to at least go 1.18.

### CODE REVIEW

**Review by nyordanoff — APPROVED** [review]

**Review by alextargov — APPROVED** [review]

**Review by alextargov — APPROVED** [review]

**Review by StanislavStefanov — DISMISSED** [review]

**Review by StefanCholakov — APPROVED** [review]

**Review by krasish — DISMISSED** [review]

**Review by PetarTodorovv — COMMENTED** [review]
Found that in the schema-migrator component the buildpack image is still 1.17 - https://github.com/kyma-incubator/compass/blob/5be8932adc0c653f7c3eee03c1341b5426dbd76a/components/schema-migrator/Makefile#L3
Should we update it?

**Comment by NickyMateev** [comment]
> Found that in the schema-migrator component the buildpack image is still 1.17 -
> 
> https://github.com/kyma-incubator/compass/blob/5be8932adc0c653f7c3eee03c1341b5426dbd76a/components/schema-migrator/Makefile#L3
> 
> 
> Should we update it?

I tried doing that, but once I did some seemingly unrelated SQL error started occurring in the component-schema-migrator at the end of the db dump insertion:

```
ERROR:  syntax error at or near "FUNCTION"
[0969] | LINE 3:    EXECUTE FUNCTION postgraphile_watch.notify_watchers_ddl()...
```

After some time spent I couldn't resolve it and decided to fall back to 1.17, because the schema migrator doesn't really have anything go-related so it shouldn't be that big of a deal.

**Review by PetarTodorovv — APPROVED** [review]

**Review by alextargov — APPROVED** [review]

**Review by desislavaa — APPROVED** [review]

**Pull request merged**
