### PR TITLE
Revert webhook parameters

### PR DESCRIPTION
**Pull request by alextargov**
**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- https://github.com/kyma-incubator/compass/pull/2869/

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by NickyMateev — APPROVED** [review]

**Comment by alextargov** [comment]
reset-vm

**Review by PetarTodorovv — APPROVED** [review]

**Pull request merged**
