### PR TITLE
Create get formation by name endpoint

### PR DESCRIPTION
**Pull request by nickormushev**
**Description**

Changes proposed in this pull request:
- Add a new endpoint that allows to get a formation by name for a tenant

**Related issue(s)**

- ...

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

### CODE REVIEW

**Review by PetarTodorovv — APPROVED** [review]
I approved the PR, only if I can ask you to add a brief description to the PR. Thanks!

**Review by nkanchev — APPROVED** [review]

**Pull request merged**
