### PR TITLE
Fix local Compass run script

### LINKED ISSUE #1518: Local Minikube installation of Compass needs Tiller secrets deployed first
**Description**

Running the Compass locally in Minikube using the `run.sh` script in the `/installation/cmd/` folder (as described [here](https://github.com/kyma-incubator/compass/blob/master/docs/compass/04-01-installation.md#local-minikube-installation)) doesn't work out of the box because the Kyma Installator requires a K8s secret `tiller-secret` deployed first. This secret is part of a yaml file that is located in `/installation/resources/tiller.yaml`.

**Expected result**

The `run.sh` script succeeds spinning up a local Compass instance.

**Actual result**

The `run.sh` script just freezes during the installation process duo to this missing `tiller-secret`.

**Steps to reproduce**

Just run the `run.sh` script without having the secrets deployed beforehand.

**Troubleshooting**

I've checked out the logs of the `kyma-installer` pod. There I saw an error message describing that there is this missing secret `tiller-secret`.

### PR DESCRIPTION
**Pull request by danielgospodinow**
**Description**

Running the Compass locally in Minikube using the `run.sh` script in the `/installation/cmd/` folder (as described [here](https://github.com/kyma-incubator/compass/blob/master/docs/compass/04-01-installation.md#local-minikube-installation)) doesn't work out of the box because the Kyma Installator requires a K8s secret `tiller-secret` deployed first. This secret is part of a yaml file that is located in `/installation/resources/tiller.yaml`.

Changes proposed in this pull request:

- Setup Tiller before starting the Kyma installation.

**Related issue(s)**

Fixes #1518

### CODE REVIEW

**Comment by danielgospodinow** [comment]
I saw that there's already an `install-tiller.sh` script which can be directly used instead of just writing again the code for it in the `install-minimal-kyma.sh` script.

**Comment by crabtree** [comment]
Hi @danielgospodinow, I think after recent changes in Kyma, you do not need the tiller at all. I also prepared a PR that removes tiller leftovers from the compass repository.

**Comment by danielgospodinow** [comment]
Okay, so I guess that we can safely just close this PR and its corresponding issue. 😄

**Pull request closed without merging**
