### PR TITLE
Add cert read scope for MAP

### PR DESCRIPTION
**Pull request by alextargov**
**Description**

Changes proposed in this pull request:
- Add cert read scope for MAP operator
- Fix RegisterApplicationFromTemplate so it would respect the "managed" label on App Inputs

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

### CODE REVIEW

**Comment by alextargov** [comment]
reset-vm

**Comment by alextargov** [comment]
reset-vm

**Review by NickyMateev — APPROVED** [review]

**Pull request merged**
