### PR TITLE
Increase golang/x/text dependency to v0.3.3

### PR DESCRIPTION
**Pull request by PetarTodorovv**
Increase golang.org/x/text dependency to version 0.3.3

### CODE REVIEW

**Review by desislavaa — APPROVED** [review]

**Review by desislavaa — CHANGES_REQUESTED** [review]
Check the changes for `pairing-adapter` and `external-services-mock` in https://github.com/kyma-incubator/compass/pull/1577
We can also set the scan results to "false positive" for `external-services-mock` instead if updating the version, but this might be the easier approach.

**Review by desislavaa — APPROVED** [review]

**Comment by PetarTodorovv** [comment]
> Check the changes for `pairing-adapter` and `external-services-mock` in #1577
> We can also set the scan results to "false positive" for `external-services-mock` instead if updating the version, but this might be the easier approach.

**Comment by PetarTodorovv** [comment]
> Check the changes for `pairing-adapter` and `external-services-mock` in #1577
> We can also set the scan results to "false positive" for `external-services-mock` instead if updating the version, but this might be the easier approach.

Discussed offline

**Review by desislavaa — APPROVED** [review]

**Pull request merged**
